language: node_js
node_js:
- lts/*
script:
- yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token:
    secure: YhwTfuz58OyP/4uWRbKJwEtAP302Y6lOk4aM1JZXKL0y9BlTAf6+MimCaItnTpZK6A5to4rVlG++d7ewkvPcEWwEzv7U4LDzjZz0pWthfadwsJaWUW7+Qf/CEWDDt/cOcvlq6f1zEaZ3fbrBXUYhlDsVoku7ke3vxyVAecnHoO9Y1KwPjxcbqHJ1dEsHKDnqX79KhR/2ejRCzvT1vneDvnUJ+eHAjswTyotmyZ0OQhWxSPFbc0rJ/Ih/TqSRRETI1oxEvAoz7ccVZtSNnJCpI2ykLydTSN9C4hS9p45OCwMhe/vL6SGABpRienSGIotHvVTd695SWigUBU1/PmwyjJJtVuwlAFXUbo5IYKE8+ViDG754YLh+GYDeNj4lJsCJt3L9/esm5nWTI7pFaBCIn8dqRMMg7Gv/V7R+GTIG9dzPa4l4zuOaIQ72Xkj4ISwfdbWkS+hSeth26ivWVdtzyw/mHJ4Fk5yI4tVC+AXo9m330nfcfaCq4q6+fOTXHP1eSEBvF/Rk1BHPUGGqsuIBwdNsMebpibd3qDaXLsCSgR8yYNSte76kE/eA+G8JEO/pjQmUBxcT8VHn07selMrLJ528pyQI3CduTg/VLmPgmm7BdCtOH1iSnkc8uq4aQAZNbXFjvlniWpqdqRp5OIoRnalKw1VYwJxdze7UumERJ1Y=
  target-branch: master
  keep-history: true
  on:
    branch: sources
