language: node_js
node_js:
  - lts/*
script:
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  target-branch: master
  keep-history: true
  on:
    branch: sources
env:
  global:
    - secure: oapp43V8PAHPvgMHsCEyJXe1pz03OO3NlHZDFkWg4wzG8XUXDEtaRZbF6mkxgTd3NybblOpkHg0Q42rN0Pv0j12E88Lucs3dXIDkjbXzM+aJA5u0Ytv3ATHMs8bN0pi2gNc/T45+94aSeIt80VEKx4m38C1lcOmQ1VTdiCN5k2jzZcq+94tSskb+u/s3dJGzohKD34cd+eregcZk4vbMN/vLxObiXf2OmkiZeMacm8aNC/oNbVAZuEno3YyRLtBv0lnVLSMxmuu1yu2e+3+JLpt/Q2XDGekfQQ9g9RK4uVyl+DStr7m//gWYa46m7bklOWi7Npdz359zWqQCztUzAEbXkLyicdstJ3NCpRmIFcJUl94Gu/zVk6mhSolHVXZgXUlOwhyzEuzDpe23gLWt3hCF0HKSZyQNYTAw0G+MwT2jwZz7f9SAr5iLzC3+2Wk2OGhR06cZdxBPYNAildashMkCHkHkr5jQbqXlEPe+8a22wkml2vGIxq9zkDXe1dC4Bsl+Jq6hjqhXRXDJWAn1PIV8TKbeAfvTxQhWnwc7VsoegC/xSauHx9IjajWNRYH1XpSVF7GZix6PErhRKXeuSMOex8oQTl6rnGk6mauxPeMzIneDo9l6LGIQNYS0qFU5PRdgfLPa6VsqnyypMe6oczCHJjWPMYdt43KOynkJ2e8=
    - secure: fdp5XtQHXg75xrC+xLsDomp83enK5A2J798Lcsj4EuUJEFHvwOm6HJDPK9/nuoFijrEZF2ASoHZaIneBrVifLv0u/OvnIjdrG3vih26ALK9Pz4ZN4+dIaTfjng9Pdo1Kp75oxu4g9LVM5Q6CmWfcU+QXCLGiaQzvxI/kKHcgmK7goO9qPCbXOyj7Ut1XcE2I/M3As7V74rDHTyqRhDYkxIQ3OfiTFo36uqVY+QCAW2u39hPEfYASJZ7teVieMxbUNXmZla+VON/1nGT+WMyrM7GS9TRy0ebQjQtUDDdJWVku8ezLhwfAg99mkUjm3Kdw0sODl0vi0UOsrpYuAT17JC/3WCEsUvzUrlea+btDmUJusToTGiJHQ6oxF9QsRlnuEWKRi5egp/xJLR2PCxtibT8bsi1j+abbLHA44SO3g6yBQaeZTfW3yfc+6Gs14QLdmJh5n10cgG1F5m7YYnUJXT85yXBlh5Del5cPPZR4Rz53ltjfGuhhS465FLOENLexIxHVUjkIcnJore5qppDPfL9Tul14c+q0q1FAtsUStgH53DjjHcRYQRHsWS7nVk7S30HrJqRq8lVWoR6w55Hfjgnn3r9BMaZnIFSaJsiiiLB5Z4qquZxF6NHmysbsgrRQjg80dWwaO0oAyjHtxDbNTfPz3DEYtvqh2CLsgKa7rH8=
