language: node_js
node_js:
- lts/*
script:
- yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token:
    secure: LD3ZMJ8tm1qHK8SgTvjtehpaWSiXuDiYjsQcd6I58tcHjvpFHO4LQf1iwtc7Q7QgLYz9Zdd7rxRVKic5YpYvslHMXtlWJ4+ZoMcBLT7/c/Cg83NPVlhYAdzFVUqWYHAIohr7rGQdEvVl0s1aVIAsOMYZfoSanZRQz3hWgg1dM7yLKoa262Pb6hgRn32rCrYzwlT7dmNJFhrp+iplVB43AmBFJjRQn3HJgVyW8GdXm4eCAZUw67VC1SohHPN2vyApBC7Qz0+gjJyOVhn7aBhJ2cvIomqtN/bOuDP5r3laZPgskQVN/8qptNvvf+ZQ+upzjqttrd0xR6mUF3mygshFVs4VUEtfJMx5ey4opb0aeQVD1H1sdfkdop16y1RFE8O55GvQvbwVyWRG2qWTb8zbbIUkZ2ZSfpSiPbUSHCN1dN8TQ1ENMBmIBkSwjeydI1wu+B07TwkzZjMHm5kv02kEtlcEkwvnakVIzH4bMt6r15sRVt7HxqUbVzR0jgLikptDgNPm8VYLaOnhCJXREpMywrL2/t46zFXIgRYVbd9Wb2FpwHWVSomyZXakG8yz2Enj3Iz1lx4Q0LuOIpagSA2i4UQtiIePVPszEGRqCl05dpuQaPlzvXtvXwZF9A3kA5+hZOPPyWdhiYg9ImCC0OOAf+mp2vvQDUXqzIt3++YlXfM=
  target-branch: master
  keep-history: true
  on:
    branch: sources
